### ISSUE TITLE
SearchResponse and SearchResponseHits do not reflect actual return keys

### ISSUE THREAD

**Issue by Lamarcke** [manticoresoftware/manticoresearch-javascript#18]
I'm building a new project using this library (great work Manticore team!).
I'm using Typescript, so i made the effort to declare custom types for this library alone. After the initial setup, i've noticed that `SearchResponse` and `SearchResponseHits` have `camelCase` key names, while the actual returned result is in `snake_case`. 

Is this intentional? Thanks in advance.

**Comment by sanikolaev** [comment]
Thanks for noticing this. We'll need to review the code style.

BTW have you considered using the [typescript client](https://github.com/manticoresoftware/manticoresearch-typescript) we added recently?

**Comment by Lamarcke** [comment]
> Thanks for noticing this. We'll need to review the code style.
> 
> BTW have you considered using the [typescript client](https://github.com/manticoresoftware/manticoresearch-typescript) we added recently?

Wow, i honestly didn't know about that! Great work!

It's not listed in the main Manticore page, so i didn't know about it. I will definetly check it out!

**Comment by sanikolaev** [comment]
> Is this intentional? 

We've discussed it and it looks ok. We use `snake_case` in the native JSON protocol of Manticore Search (e.g. `total_relation` - https://github.com/manticoresoftware/openapi/blob/722931a1c399975a8d027f5b0682f83d084fbfa8/manticore.yml#L805), but when OpenAPI generates the Javascript client it converts that to `camelCase` since it's more common in Javascript.
